import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { bumpVersion, run } from "./bump-version.mjs";

async function writeJson(path, value) {
  await writeFile(path, `${JSON.stringify(value, null, 2)}\n`);
}

async function readJson(path) {
  return JSON.parse(await readFile(path, "utf8"));
}

async function withFixture(testFn) {
  const root = await mkdtemp(join(tmpdir(), "launcher-bump-version-"));
  try {
    await writeJson(join(root, "package.json"), {
      name: "launcher",
      version: "0.2.0",
    });
    await writeJson(join(root, "package-lock.json"), {
      name: "launcher",
      version: "0.2.0",
      packages: {
        "": {
          name: "launcher",
          version: "0.2.0",
        },
      },
    });
    await writeJson(join(root, "tauri.conf.json"), {
      productName: "Launcher",
      version: "0.2.0",
    });
    await writeFile(
      join(root, "Cargo.toml"),
      '[package]\nname = "launcher"\nversion = "0.2.0"\nedition = "2021"\n\n[dependencies]\nserde = { version = "1" }\n',
    );
    await writeFile(
      join(root, "Cargo.lock"),
      '# This file is automatically @generated by Cargo.\n\n[[package]]\nname = "launcher"\nversion = "0.2.0"\n\n[[package]]\nname = "serde"\nversion = "1.0.0"\n',
    );

    await testFn(root);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

await withFixture(async (root) => {
  assert.equal(bumpVersion("0.2.0", "patch"), "0.2.1");
  assert.equal(bumpVersion("0.2.0", "minor"), "0.3.0");
  assert.equal(bumpVersion("0.2.0", "major"), "1.0.0");
  assert.equal(bumpVersion("0.2.0", "1.2.3"), "1.2.3");

  const result = await run(["minor"], {
    root,
    files: {
      packageJson: "package.json",
      packageLock: "package-lock.json",
      tauriConfig: "tauri.conf.json",
      cargoToml: "Cargo.toml",
      cargoLock: "Cargo.lock",
    },
  });

  assert.deepEqual(result, { from: "0.2.0", to: "0.3.0" });
  assert.equal((await readJson(join(root, "package.json"))).version, "0.3.0");
  assert.equal((await readJson(join(root, "package-lock.json"))).version, "0.3.0");
  assert.equal((await readJson(join(root, "package-lock.json"))).packages[""].version, "0.3.0");
  assert.equal((await readJson(join(root, "tauri.conf.json"))).version, "0.3.0");
  assert.match(await readFile(join(root, "Cargo.toml"), "utf8"), /version = "0\.3\.0"/);
  assert.match(await readFile(join(root, "Cargo.lock"), "utf8"), /name = "launcher"\nversion = "0\.3\.0"/);
});

await withFixture(async (root) => {
  const packageJson = await readJson(join(root, "package.json"));
  packageJson.version = "0.2.1";
  await writeJson(join(root, "package.json"), packageJson);

  await assert.rejects(
    () =>
      run(["patch"], {
        root,
        files: {
          packageJson: "package.json",
          packageLock: "package-lock.json",
          tauriConfig: "tauri.conf.json",
          cargoToml: "Cargo.toml",
          cargoLock: "Cargo.lock",
        },
      }),
    /Version sources are not in sync/,
  );
});
